[build]
  functions = "functions" # Netlify serverless functions directory if you're using serverless functions

[dev]
  command = "npm start" # Command to start the development server locally

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200