[build]
  functions = "functions" # Netlify serverless functions directory if you're using serverless functions
  publish = "public" # Public directory that Netlify serves, change it if your static files are in a different folder

[dev]
  command = "npm start" # Command to start the development server locally

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200